# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Multi Author Blog"
license = "Unlicense"
licenselink = "https://github.com/sethmacleod/hugo-multi-author/blob/master/LICENSE.md"
description = "A simple multi-author blog theme for Hugo"
homepage = "https://github.com/sethmacleod/hugo-multi-author"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Seth MacLeod"
  homepage = "https://github.com/sethmacleod"